1)How can you get help on np.array?
 Call dir() on np.array.

 Call dir() on car.

 Note the difference. car has methods and attributes we can use.

In [1]:
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('Documents/Data-Science-Assignments/course_material/week_03/cars.csv' ,delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])

df

Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1            Buick Skylark 320  15.0          8         350.0       165.0   
2           Plymouth Satellite  18.0          8         318.0       150.0   
3                AMC Rebel SST  16.0          8         304.0       150.0   
4                  Ford Torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
401            Ford Mustang GL  27.0          4         140.0        86.0   
402          Volkswagen Pickup  44.0          4          97.0        52.0   
403              Dodge Rampage  32.0          4         135.0        84.0   
404                Ford Ranger  28.0          4         120.0        79.0   
405                 Chevy S-10  31.0          4         119.0        82.0   

     Weight  Acceleration  Model  Origin  
0    3504.0          12.0     70      US  
1    3693.0          11.5     70      US  
2    3436.0          11.0     70      US  
3    3433.0          12.0     70      US  
4    3449.0          10.5     70      US  
..      ...           ...    ...     ...  
401  2790.0          15.6     82      US  
402  2130.0          24.6     82  Europe  
403  2295.0          11.6     82      US  
404  2625.0          18.6     82      US  
405  2720.0          19.4     82      US  

[406 rows x 9 columns]

In [2]:
# To get help on np.array we can use :
# Use np.lookfor() to do a keyword search on docstrings. 
# Use np.info() for quick explanations and code examples of functions, classes, or modules. 

#import numpy as np

dir(car)


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [3]:
dir(np.array)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

2)What are the numpy datatypes for the car,mpg, horsepower and origin arrays?

In [4]:
car.dtype

dtype('O')

In [5]:
mpg.dtype

dtype('float64')

In [6]:
horsepower.dtype

dtype('float64')

3)Numpy is often imported as np. What is this action called? Why might you do this?

In [7]:
# Numpy is usually imported under the np alias.
# Alias are an alternate name for referring to the same thing. 
# When we call the statement import numpy as np , we are shortening the phrase "numpy" to "np" to make the code easier to read 
# It also helps to avoid namespace issues. 
#import numpy as np

4)Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code.

In [8]:
print(car)
car.ndim

['Chevrolet Chevelle Malibu' 'Buick Skylark 320' 'Plymouth Satellite'
 'AMC Rebel SST' 'Ford Torino' 'Ford Galaxie 500' 'Chevrolet Impala'
 'Plymouth Fury iii' 'Pontiac Catalina' 'AMC Ambassador DPL'
 'Citroen DS-21 Pallas' 'Chevrolet Chevelle Concours (sw)'
 'Ford Torino (sw)' 'Plymouth Satellite (sw)' 'AMC Rebel SST (sw)'
 'Dodge Challenger SE' "Plymouth 'Cuda 340" 'Ford Mustang Boss 302'
 'Chevrolet Monte Carlo' 'Buick Estate Wagon (sw)'
 'Toyota Corolla Mark ii' 'Plymouth Duster' 'AMC Hornet' 'Ford Maverick'
 'Datsun PL510' 'Volkswagen 1131 Deluxe Sedan' 'Peugeot 504' 'Audi 100 LS'
 'Saab 99e' 'BMW 2002' 'AMC Gremlin' 'Ford F250' 'Chevy C20' 'Dodge D200'
 'Hi 1200D' 'Datsun PL510' 'Chevrolet Vega 2300' 'Toyota Corolla'
 'Ford Pinto' 'Volkswagen Super Beetle 117' 'AMC Gremlin'
 'Plymouth Satellite Custom' 'Chevrolet Chevelle Malibu' 'Ford Torino 500'
 'AMC Matador' 'Chevrolet Impala' 'Pontiac Catalina Brougham'
 'Ford Galaxie 500' 'Plymouth Fury iii' 'Dodge Monaco (sw)'
 'Ford Count

1

In [9]:
mpg.ndim

1

In [10]:
cylinders.ndim

1

In [11]:
#All are 1-dimensional arrays. For finding dimensions we use ndim

5)How how to:
multiply the mpg array by 12.
divide the mpg array by 3.
raise the mpg array to the power of 4.
take the square root of the mpg array.

In [12]:
mpg * 12 


array([216. , 180. , 216. , 192. , 204. , 180. , 168. , 168. , 168. ,
       180. ,   0. ,   0. ,   0. ,   0. ,   0. , 180. , 168. ,   0. ,
       180. , 168. , 288. , 264. , 216. , 252. , 324. , 312. , 300. ,
       288. , 300. , 312. , 252. , 120. , 120. , 132. , 108. , 324. ,
       336. , 300. , 300. ,   0. , 228. , 192. , 204. , 228. , 216. ,
       168. , 168. , 168. , 168. , 144. , 156. , 156. , 216. , 264. ,
       228. , 216. , 276. , 336. , 360. , 360. , 372. , 420. , 324. ,
       312. , 288. , 300. , 276. , 240. , 252. , 156. , 168. , 180. ,
       168. , 204. , 132. , 156. , 144. , 156. , 228. , 180. , 156. ,
       156. , 168. , 216. , 264. , 252. , 312. , 264. , 336. , 276. ,
       336. , 324. , 156. , 168. , 156. , 168. , 180. , 144. , 156. ,
       156. , 168. , 156. , 144. , 156. , 216. , 192. , 216. , 216. ,
       276. , 312. , 132. , 144. , 156. , 144. , 216. , 240. , 252. ,
       264. , 216. , 228. , 252. , 312. , 180. , 192. , 348. , 288. ,
       240. , 228. ,

In [13]:
mpg / 3

array([ 6.        ,  5.        ,  6.        ,  5.33333333,  5.66666667,
        5.        ,  4.66666667,  4.66666667,  4.66666667,  5.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        5.        ,  4.66666667,  0.        ,  5.        ,  4.66666667,
        8.        ,  7.33333333,  6.        ,  7.        ,  9.        ,
        8.66666667,  8.33333333,  8.        ,  8.33333333,  8.66666667,
        7.        ,  3.33333333,  3.33333333,  3.66666667,  3.        ,
        9.        ,  9.33333333,  8.33333333,  8.33333333,  0.        ,
        6.33333333,  5.33333333,  5.66666667,  6.33333333,  6.        ,
        4.66666667,  4.66666667,  4.66666667,  4.66666667,  4.        ,
        4.33333333,  4.33333333,  6.        ,  7.33333333,  6.33333333,
        6.        ,  7.66666667,  9.33333333, 10.        , 10.        ,
       10.33333333, 11.66666667,  9.        ,  8.66666667,  8.        ,
        8.33333333,  7.66666667,  6.66666667,  7.        ,  4.33

In [14]:
mpg ** 4

array([ 104976.    ,   50625.    ,  104976.    ,   65536.    ,
         83521.    ,   50625.    ,   38416.    ,   38416.    ,
         38416.    ,   50625.    ,       0.    ,       0.    ,
             0.    ,       0.    ,       0.    ,   50625.    ,
         38416.    ,       0.    ,   50625.    ,   38416.    ,
        331776.    ,  234256.    ,  104976.    ,  194481.    ,
        531441.    ,  456976.    ,  390625.    ,  331776.    ,
        390625.    ,  456976.    ,  194481.    ,   10000.    ,
         10000.    ,   14641.    ,    6561.    ,  531441.    ,
        614656.    ,  390625.    ,  390625.    ,       0.    ,
        130321.    ,   65536.    ,   83521.    ,  130321.    ,
        104976.    ,   38416.    ,   38416.    ,   38416.    ,
         38416.    ,   20736.    ,   28561.    ,   28561.    ,
        104976.    ,  234256.    ,  130321.    ,  104976.    ,
        279841.    ,  614656.    ,  810000.    ,  810000.    ,
        923521.    , 1500625.    ,  531441.    ,  45697

In [15]:
np.sqrt(mpg)

array([4.24264069, 3.87298335, 4.24264069, 4.        , 4.12310563,
       3.87298335, 3.74165739, 3.74165739, 3.74165739, 3.87298335,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       3.87298335, 3.74165739, 0.        , 3.87298335, 3.74165739,
       4.89897949, 4.69041576, 4.24264069, 4.58257569, 5.19615242,
       5.09901951, 5.        , 4.89897949, 5.        , 5.09901951,
       4.58257569, 3.16227766, 3.16227766, 3.31662479, 3.        ,
       5.19615242, 5.29150262, 5.        , 5.        , 0.        ,
       4.35889894, 4.        , 4.12310563, 4.35889894, 4.24264069,
       3.74165739, 3.74165739, 3.74165739, 3.74165739, 3.46410162,
       3.60555128, 3.60555128, 4.24264069, 4.69041576, 4.35889894,
       4.24264069, 4.79583152, 5.29150262, 5.47722558, 5.47722558,
       5.56776436, 5.91607978, 5.19615242, 5.09901951, 4.89897949,
       5.        , 4.79583152, 4.47213595, 4.58257569, 3.60555128,
       3.74165739, 3.87298335, 3.74165739, 4.12310563, 3.31662

6)What is the ___ of horsepower?
sum
min
max
median
Optional: mode (May need to google help)

In [16]:
horsepower.sum()

42033.0

In [17]:
horsepower.min()

0.0

In [18]:
horsepower.max()

230.0

In [19]:
np.median(horsepower)

93.5

In [20]:
import numpy as np
from scipy import stats
mode = stats.mode(horsepower)
print(mode)

ModeResult(mode=array([150.]), count=array([22]))


7)Select a subset of acceleration.
Select only the first 5 elements.
Select every other element (new selection).

In [21]:
import numpy as np
print(acceleration[0:5])  # Select only the first 5 elements.

print(acceleration[::2])  #Select every other element (new selection).


[12.  11.5 11.  12.  10.5]
[12.  11.  10.5  9.  10.  17.5 11.  11.   8.   9.5 15.  15.5 14.5 17.5
 17.5 15.  15.  18.5 15.5 19.  13.  15.5 15.5 11.5 13.  12.  13.5 15.
 14.  19.5 19.  19.  15.5 23.5 16.5 12.  13.  11.  13.5 13.5 14.  14.
 18.  18.  17.  15.  13.  13.  12.5 12.  14.5 11.  16.5 16.  16.  14.
 13.  15.  19.5 13.5 14.  13.  19.5 14.  11.  13.5 16.5 16.  19.  21.
 17.  16.5 14.5 16.  16.5 14.5 19.  15.5 15.  16.  16.  19.5 14.  13.5
 18.5 19.  13.5 16.  16.  13.5 17.  14.  15.  14.5 17.5 16.9 17.7 13.
 13.9 15.4 17.6 22.2 14.2 17.7 16.2 12.2 16.4 15.7 21.9 16.7 12.  14.
 14.8 15.5 12.5 13.7 16.4 17.7 11.1 12.2 14.5 18.2 17.  16.4 14.5 13.5
 14.4 18.6 15.5 12.8 18.2 15.4 17.2 16.7 15.1 13.4 13.7 14.2 14.5 16.7
 14.9 13.6 15.8 16.6 18.2 18.2 15.4 13.2 14.9 15.  14.  14.4 20.1 24.8
 13.2 19.2 16.  12.9 14.7 15.5 16.5 20.1 15.8 17.5 15.2 14.4 21.7 19.9
 13.8 18.  11.4 15.1 17.  16.4 12.6 16.9 16.1 19.4 16.  16.2 14.2 14.4
 14.8 20.4 19.6 13.8 19.  16.6 18.6 16.2 18.  20.5 18.2 

8)Show how to select the number 99 in the array below.
select_99 = np.array([[1,2,3],
                      [4,5,99]])

In [22]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])

select_99 [1,2]

99

9)Select the last element in each subarray (do this with one operation.)
In [ ]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [23]:
import numpy as np
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


print(select_more[: , 2])

[3 6 9]


10)Use the built-in np.lookfor() function to search for 'log'.
Use the function you find and apply it to mpg

In [24]:
import numpy as np
a = np.lookfor('log') 
print(a)


Search results for 'log'
------------------------
numpy.log
    Natural logarithm, element-wise.
numpy.log2
    Base-2 logarithm of `x`.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, element-wise.
numpy.logspace
    Return numbers spaced evenly on a log scale.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.logical_or
    Compute the truth value of x1 OR x2 element-wise.
numpy.logical_and
    Compute the truth value of x1 AND x2 element-wise.
numpy.logical_not
    Compute the truth value of NOT x element-wise.
numpy.logical_xor
    Compute the truth value of x1 XOR x2, element-wise.
numpy.ma.log
    Natural logarithm, element-wise.
numpy.ma.log2
    Base-2 logarithm of `x`.
numpy.ma.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.rec

In [25]:
np.log2(mpg)

array([4.169925  , 3.9068906 , 4.169925  , 4.        , 4.08746284,
       3.9068906 , 3.80735492, 3.80735492, 3.80735492, 3.9068906 ,
             -inf,       -inf,       -inf,       -inf,       -inf,
       3.9068906 , 3.80735492,       -inf, 3.9068906 , 3.80735492,
       4.5849625 , 4.45943162, 4.169925  , 4.39231742, 4.7548875 ,
       4.70043972, 4.64385619, 4.5849625 , 4.64385619, 4.70043972,
       4.39231742, 3.32192809, 3.32192809, 3.45943162, 3.169925  ,
       4.7548875 , 4.80735492, 4.64385619, 4.64385619,       -inf,
       4.24792751, 4.        , 4.08746284, 4.24792751, 4.169925  ,
       3.80735492, 3.80735492, 3.80735492, 3.80735492, 3.5849625 ,
       3.70043972, 3.70043972, 4.169925  , 4.45943162, 4.24792751,
       4.169925  , 4.52356196, 4.80735492, 4.9068906 , 4.9068906 ,
       4.95419631, 5.12928302, 4.7548875 , 4.70043972, 4.5849625 ,
       4.64385619, 4.52356196, 4.32192809, 4.39231742, 3.70043972,
       3.80735492, 3.9068906 , 3.80735492, 4.08746284, 3.45943

11)You your google skills to find the unique items in origin. (This may not have been covered in the readings.)

In [26]:
np.unique(origin)

array(['Europe', 'Japan', 'US'], dtype=object)

12)Create a 2D array and print its shape as well as ndim. (Any shape is fine)
Create a 3D array and print its shape as well as ndim.

Create a 4D array and print its shape as well as ndim. It's hard to visualize 4-Dimensions but numpy can do it with ease!

In [27]:
import numpy as np
a = np.array([[1 , 2 , 3 , 4] , [5 , 6 , 7 , 8]] , dtype = 'int16')
print("dimension:" , a.ndim)
print("shape:" , a.shape)
print(a)

b = np.array([[[1 , 2],[3 , 4]] , [[5 ,6] ,[7 , 8]]])
print("Dimension:" , b.ndim)
print("Shape:" , b.shape)
print(b)

c = np.array([[[[1 , 2 ,3 , 4] , [5 ,6 , 7 , 8]] ,[[9 , 10 , 11 ,12] , [13 , 14 , 15 , 16]]]])
print(c)
print(c.ndim)
print(c.shape)

dimension: 2
shape: (2, 4)
[[1 2 3 4]
 [5 6 7 8]]
Dimension: 3
Shape: (2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]]]
4
(1, 2, 2, 4)


13)Use boolean indexing to create an array of True/False using origin and the value 'US'.

In [29]:
a = origin == "US" # boolean indexing to create an array of True/False using origin and the value 'US'
print(a)

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True False  True  True  True
 False False False False False False  True  True  True  True  True False
  True False  True False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False False False
 False False False  True False  True False  True  True  True  True  True
  True  True  True  True  True  True False  True  True  True  True False
 False False False  True False False  True False  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True False  True False False  True
  True False  True  True False False False False  True False False  True
  True  True  True  True False  True False  True  True  True  True  True
  True  True  True  True False False False False False  True False False
 False False False  True  True  True  True  True  T

Apply your index (from above) to the car array. You should now only see cars that are of US origin.

In [30]:
a = origin == "US" # boolean indexing to create an array of True/False using origin and the value 'US'
print(a)

arr = car[a]    #cars that are of US origin.
print(arr)

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True False  True  True  True
 False False False False False False  True  True  True  True  True False
  True False  True False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False False False
 False False False  True False  True False  True  True  True  True  True
  True  True  True  True  True  True False  True  True  True  True False
 False False False  True False False  True False  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True False  True False False  True
  True False  True  True False False False False  True False False  True
  True  True  True  True False  True False  True  True  True  True  True
  True  True  True  True False False False False False  True False False
 False False False  True  True  True  True  True  T

Optional questions : 1)What is an identity matrix? Create an identiy matrix of size 5 using an np method.

In [31]:
#Identity matrix is a square matrix 
import numpy as np
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

2)Transpose the following array.

transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


In [32]:
import numpy as np
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
print(transpose_me)
print(transpose_me.transpose())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


3)Why does this multiplication operation fail?

arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

In [33]:
#Following multiplication has failed as these two arrays cannot be broadcasted together as they are of different shapes (3,3) (2,3).
# For broadcasting they need to be of the same shape.


4)What is the average horsepower for Europe cars?

In [34]:
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('Documents/Data-Science-Assignments/course_material/week_03/cars.csv' ,delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])



In [35]:
hparr = horsepower [origin == 'Europe']
avgHP= np.mean(hparr)
print(avgHP)

78.78082191780823


5)On average are Japanese cars more fuel efficient than US cars? 

In [36]:
mpgarr = mpg [origin == 'Japan']
avgmpg= np.mean(mpgarr)
print(avgmpg)
mpgarr1 = mpg [origin == 'US']
avgmpg1 = np.mean(mpgarr1)
print(avgmpg1)
if avgmpg > avgmpg1:
     print("Japanese cars are more fuel efficient")
else:
    print("US cars are less fuel efficient")


30.450632911392404
19.688188976377955
Japanese cars are more fuel efficient


6)What is the correlation coefficient of `mpg` and `weight`?

In [37]:
r = np.corrcoef(mpg,weight)
print(r)

[[ 1.         -0.78750994]
 [-0.78750994  1.        ]]


7)Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 

In [38]:
#Numpy are preferred more over python list because of the follwing reasons:
# 1) Save coding time- 1)No for loops :many vectors and  matrix operations save coding time.

# 2)Faster execution- 1) Single type of each field to avoid type checking. 
#                      2) Use contiguous blocks of memory.

#Uses less memory -    1) It has compact datatypes like uint8 and float16.

#Python list is preferred when we want to use heterogenous data types.
#thislist = (["apple" , True , 67 , "cherry" ,43.9])